stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync
    - mkdir -p ~/.ssh
    - echo "$SERVER_KEY"
    - echo "$SERVER_IP"
    - echo "$SERVER_USER"
    - printf "%s" "$SERVER_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - head -n 5 ~/.ssh/id_rsa 
    - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
    - ls -la ~/.ssh
  script:
    - echo "$SERVER_KEY"
    - echo "$SERVER_IP"
    - echo "$SERVER_USER"
    - echo "Testing SSH connection..."
    - ssh -i ~/.ssh/id_rsa -vvv $SERVER_USER@$SERVER_IP "echo 'SSH OK!'"
    - echo "Starting rsync..."
    - rsync -avz -e "ssh -v" ./ $SERVER_USER@$SERVER_IP:/home/materalist/project
    - ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "
        cd /home/materalist/project &&
        rm .env &&
        mv .env.production .env &&
        docker-compose pull &&
        docker-compose up -d --build
      "
  only:
    - main