stages:
  - test-client
  - test-server
  - deploy

client:tests:
  stage: test-client
  image: node:16
  variables:
    npm_config_optional: false
  before_script:
    - echo "Installing system deps (xvfb + Cypress libs)…"
    - apt-get update && apt-get install -y \
        xvfb \
        libgtk2.0-0 \
        libgtk-3-0 \
        libnotify-dev \
        libgconf-2-4 \
        libnss3 \
        libxss1 \
        libxtst6
    - echo "Installing client deps…"
    - cd client
    - npm ci
  script:
    - npm run type-check

    - echo "Running Cypress under Xvfb…"
    - xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npm run cy:run
  only:
    - main

server:tests:
  stage: test-server
  image: node:16
  before_script:
    - cd server
    - npm ci
  script:
    - echo "Running server tests…"
    - npm run test
  needs:
    - client:tests
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  needs:
    - client:tests
    - server:tests
  before_script:
    - apk add --no-cache openssh-client rsync
    - mkdir -p ~/.ssh
    - echo "$SERVER_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
  script:
    - echo "Syncing files…"
    - rsync -avz -e "ssh -v" ./ $SERVER_USER@$SERVER_IP:/home/materalist/project
    - ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "
        cd /home/materalist/project &&
        rm .env &&
        mv .env.production .env &&
        docker-compose pull &&
        docker-compose up -d --build
      "
  only:
    - main
