import {PluginEditorBlock} from "@/editor/block/base/plugin/PluginEditorBlock";
import {PluginPropertyBase, SelectPluginProperty} from "@/editor/block/base/plugin/PluginProperty";
import {SelectProperty} from "@/editor/property/type/SelectProperty";
import {CodeEditorBlock} from "@/editor/block/base/code/CodeEditorBlock";
import {BooleanProperty} from "@/editor/property/type/BooleanProperty";

export class LanguageProperty<T extends CodeEditorBlock = CodeEditorBlock> extends SelectProperty<T> {
    constructor() {
        super("Language", "language",
            [
            {"value":"auto", "label":"Auto"},
            {"value":"1c","label":"1C"},
            {"value":"abnf","label":"ABNF"},
            {"value":"accesslog","label":"Access logs"},
            {"value":"ada","label":"Ada"},
            {"value":"arduino","label":"Arduino (C++ w/Arduino libs)"},
            {"value":"armasm","label":"ARM assembler"},
            {"value":"avrasm","label":"AVR assembler"},
            {"value":"actionscript","label":"ActionScript"},
            {"value":"angelscript","label":"AngelScript"},
            {"value":"apache","label":"Apache"},
            {"value":"applescript","label":"AppleScript"},
            {"value":"arcade","label":"Arcade"},
            {"value":"asciidoc","label":"AsciiDoc"},
            {"value":"aspectj","label":"AspectJ"},
            {"value":"autohotkey","label":"AutoHotkey"},
            {"value":"autoit","label":"AutoIt"},
            {"value":"awk","label":"Awk"},
            {"value":"bash","label":"Bash"},
            {"value":"basic","label":"Basic"},
            {"value":"bnf","label":"BNF"},
            {"value":"brainfuck","label":"Brainfuck"},
            {"value":"csharp","label":"C#"},
            {"value":"c","label":"C"},
            {"value":"cpp","label":"C++"},
            {"value":"cal","label":"C/AL"},
            {"value":"cos","label":"Cache Object Script"},
            {"value":"cmake","label":"CMake"},
            {"value":"coq","label":"Coq"},
            {"value":"csp","label":"CSP"},
            {"value":"css","label":"CSS"},
            {"value":"capnproto","label":"Cap’n Proto"},
            {"value":"clojure","label":"Clojure"},
            {"value":"coffeescript","label":"CoffeeScript"},
            {"value":"crmsh","label":"Crmsh"},
            {"value":"crystal","label":"Crystal"},
            {"value":"d","label":"D"},
            {"value":"dart","label":"Dart"},
            {"value":"dpr","label":"Delphi"},
            {"value":"diff","label":"Diff"},
            {"value":"django","label":"Django"},
            {"value":"dns","label":"DNS Zone file"},
            {"value":"dockerfile","label":"Dockerfile"},
            {"value":"dos","label":"DOS"},
            {"value":"dsconfig","label":"dsconfig"},
            {"value":"dts","label":"DTS (Device Tree)"},
            {"value":"dust","label":"Dust"},
            {"value":"ebnf","label":"EBNF"},
            {"value":"elixir","label":"Elixir"},
            {"value":"elm","label":"Elm"},
            {"value":"erlang","label":"Erlang"},
            {"value":"excel","label":"Excel"},
            {"value":"fsharp","label":"F#"},
            {"value":"fix","label":"FIX"},
            {"value":"fortran","label":"Fortran"},
            {"value":"gcode","label":"G-Code"},
            {"value":"gams","label":"Gams"},
            {"value":"gauss","label":"GAUSS"},
            {"value":"gherkin","label":"Gherkin"},
            {"value":"go","label":"Go"},
            {"value":"golo","label":"Golo"},
            {"value":"gradle","label":"Gradle"},
            {"value":"graphql","label":"GraphQL"},
            {"value":"groovy","label":"Groovy"},
            {"value":"xml","label":"HTML, XML"},
            {"value":"http","label":"HTTP"},
            {"value":"haml","label":"Haml"},
            {"value":"handlebars","label":"Handlebars"},
            {"value":"haskell","label":"Haskell"},
            {"value":"haxe","label":"Haxe"},
            {"value":"hy","label":"Hy"},
            {"value":"ini","label":"Ini, TOML"},
            {"value":"inform7","label":"Inform7"},
            {"value":"irpf90","label":"IRPF90"},
            {"value":"json","label":"JSON"},
            {"value":"java","label":"Java"},
            {"value":"javascript","label":"JavaScript"},
            {"value":"julia","label":"Julia"},
            {"value":"julia-repl","label":"Julia REPL"},
            {"value":"kotlin","label":"Kotlin"},
            {"value":"tex","label":"LaTeX"},
            {"value":"leaf","label":"Leaf"},
            {"value":"lasso","label":"Lasso"},
            {"value":"less","label":"Less"},
            {"value":"ldif","label":"LDIF"},
            {"value":"lisp","label":"Lisp"},
            {"value":"livecodeserver","label":"LiveCode Server"},
            {"value":"livescript","label":"LiveScript"},
            {"value":"lua","label":"Lua"},
            {"value":"makefile","label":"Makefile"},
            {"value":"markdown","label":"Markdown"},
            {"value":"mathematica","label":"Mathematica"},
            {"value":"matlab","label":"Matlab"},
            {"value":"maxima","label":"Maxima"},
            {"value":"mel","label":"Maya Embedded Language"},
            {"value":"mercury","label":"Mercury"},
            {"value":"mips","label":"MIPS Assembler"},
            {"value":"mizar","label":"Mizar"},
            {"value":"mojolicious","label":"Mojolicious"},
            {"value":"monkey","label":"Monkey"},
            {"value":"moonscript","label":"Moonscript"},
            {"value":"n1ql","label":"N1QL"},
            {"value":"nsis","label":"NSIS"},
            {"value":"nginx","label":"Nginx"},
            {"value":"nim","label":"Nim"},
            {"value":"nix","label":"Nix"},
            {"value":"ocaml","label":"OCaml"},
            {"value":"objectivec","label":"Objective C"},
            {"value":"glsl","label":"OpenGL Shading Language"},
            {"value":"openscad","label":"OpenSCAD"},
            {"value":"ruleslanguage","label":"Oracle Rules Language"},
            {"value":"oxygene","label":"Oxygene"},
            {"value":"pf","label":"PF"},
            {"value":"php","label":"PHP"},
            {"value":"parser3","label":"Parser3"},
            {"value":"perl","label":"Perl"},
            {"value":"plaintext","label":"Plaintext"},
            {"value":"pony","label":"Pony"},
            {"value":"pgsql","label":"PostgreSQL & PL/pgSQL"},
            {"value":"powershell","label":"PowerShell"},
            {"value":"processing","label":"Processing"},
            {"value":"prolog","label":"Prolog"},
            {"value":"properties","label":"Properties"},
            {"value":"proto","label":"Protocol Buffers"},
            {"value":"puppet","label":"Puppet"},
            {"value":"python","label":"Python"},
            {"value":"profile","label":"Python profiler results"},
            {"value":"python-repl","label":"Python REPL"},
            {"value":"k","label":"Q"},
            {"value":"qml","label":"QML"},
            {"value":"r","label":"R"},
            {"value":"reasonml","label":"ReasonML"},
            {"value":"rib","label":"RenderMan RIB"},
            {"value":"rsl","label":"RenderMan RSL"},
            {"value":"graph","label":"Roboconf"},
            {"value":"ruby","label":"Ruby"},
            {"value":"rust","label":"Rust"},
            {"value":"SAS","label":"SAS"},
            {"value":"scss","label":"SCSS"},
            {"value":"sql","label":"SQL"},
            {"value":"p21","label":"STEP Part 21"},
            {"value":"scala","label":"Scala"},
            {"value":"scheme","label":"Scheme"},
            {"value":"scilab","label":"Scilab"},
            {"value":"shell","label":"Shell"},
            {"value":"smali","label":"Smali"},
            {"value":"smalltalk","label":"Smalltalk"},
            {"value":"sml","label":"SML"},
            {"value":"stan","label":"Stan"},
            {"value":"stata","label":"Stata"},
            {"value":"stylus","label":"Stylus"},
            {"value":"subunit","label":"SubUnit"},
            {"value":"swift","label":"Swift"},
            {"value":"tcl","label":"Tcl"},
            {"value":"tap","label":"Test Anything Protocol"},
            {"value":"thrift","label":"Thrift"},
            {"value":"tp","label":"TP"},
            {"value":"twig","label":"Twig"},
            {"value":"typescript","label":"TypeScript"},
            {"value":"vbnet","label":"VB.Net"},
            {"value":"vbscript","label":"VBScript"},
            {"value":"vhdl","label":"VHDL"},
            {"value":"vala","label":"Vala"},
            {"value":"verilog","label":"Verilog"},
            {"value":"vim","label":"Vim Script"},
            {"value":"axapta","label":"X++"},
            {"value":"x86asm","label":"x86 Assembly"},
            {"value":"xl","label":"XL"},
            {"value":"xquery","label":"XQuery"},
            {"value":"yml","label":"YAML"},
            {"value":"zephir","label":"Zephir"}]
        );
    }

    getID(): string {
        return super.getID();
    }

    override getPriority(): number {
        return 1;
    }

    applyValue(value: string): boolean {
        this.blocks[0].setLanguage(value);
        return true;
    }

    isVisible(): boolean {
        return this.blocks.length === 1;
    }

    recalculateValues(change: (value: string) => void): void {
        change(this.blocks[0].getLanguage());
    }
}
