FROM node:20
WORKDIR /app
COPY package*.json ./
RUN npm install

ARG HOMEPAGE_DOMAIN
RUN echo "\nHOME_LINK=${HOMEPAGE_DOMAIN}" >> .env
ARG DOCS_DOMAIN
RUN echo "\nDOCS_LINK=${DOCS_DOMAIN}" >> .env
ARG APP_DOMAIN
RUN echo "\nAPP_LINK=${APP_DOMAIN}" >> .env

CMD ["npm", "run", "start:dev"]

EXPOSE 3000