FROM node:20 as builder
WORKDIR /app
COPY . .
RUN npm install

ARG HOMEPAGE_DOMAIN
RUN echo "\nHOME_LINK=${HOMEPAGE_DOMAIN}" >> .env
ARG DOCS_DOMAIN
RUN echo "\nDOCS_LINK=${DOCS_DOMAIN}" >> .env
ARG APP_DOMAIN
RUN echo "\nAPP_LINK=${APP_DOMAIN}" >> .env

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80